Repository FerMod/EventDispatcher, pull requests merged in 2019-05, with the labels that each got.

#13 Update docs
  CONTRIBUTING.md
  README.md
  pom.xml
Labels: documentation

#16 Add TravisCI scripts and project cleanup
  .editorconfig
  .gitattributes
  .travis.yml
  CHANGELOG.md
  deploy_docs.sh
  doxygen/extract-template.sh
  doxygen/generate_docs.sh
  doxygen/run_doxygen.sh
  install-doxygen.sh
  scripts/deploy-docs.sh
  scripts/generate-tree.sh
  scripts/install-doxygen.sh
  scripts/run-doxygen.sh
  scripts/update-maven-version.sh
  update_maven_version.sh
Labels: cleanup, enhancement, feature

#25 Add sonar cloud support
  .travis.yml
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  pom.xml
  scripts/deploy-docs.sh
  scripts/generate-docs.sh
  scripts/sonar-scan.sh
  sonar-project.properties
  src/main/java/com/fermod/event/EventPublisher.java
  src/main/java/com/fermod/observer/ObservedValue.java
Labels: cleanup, enhancement

#30 New test and documentation
  .classpath
  README.md
  pom.xml
  src/main/resources/EventDisp_Diagram.png
  src/test/java/com/fermod/ObservableValueTest.java
  src/test/java/com/fermod/annotations/ArrayArgumentsProvider.java
  src/test/java/com/fermod/annotations/ArraySource.java
  src/test/java/com/fermod/annotations/ArraySources.java
Labels: documentation, enhancement

#35 Update changelog
  CHANGELOG.md
Labels: cleanup, documentation, enhancement
